# Generated by Django 5.1.6 on 2025-03-01 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDiretor', models.CharField(max_length=255)),
                ('idade', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloFilme', models.CharField(max_length=255)),
                ('anoFilme', models.IntegerField()),
                ('generoFilme', models.CharField(max_length=255)),
                ('omdbId', models.CharField(max_length=255, unique=True)),
                ('diretoFilme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes', to='omdb_app.diretor')),
            ],
        ),
    ]
